export const ApiTopPrdcts = [
  {
    id: 1,
    src: "https://images-na.ssl-images-amazon.com/images/I/81au7a6yf6L._SL1500_.jpg",
    product:"Housse",
    price: 5800,
    disc: "house standard pour tt type de vehicules",
    quantity: 1,
    totalQty : 100,
  },
  {
    id: 2,
    src: "https://ae01.alicdn.com/kf/HTB1BI1sSVXXXXXcXXXXq6xXFXXXB/De-luxe-3D-Surround-Complet-Voiture-Housse-de-Si-ge-En-Cuir-PU-Si-ge-Couvre.jpg",
    product:"Housse cuir",
    price: 14000,
    disc: "",
    quantity: 1,
    totalQty : 100,
  },
  {
    id: 3,
    src: "https://ae01.alicdn.com/kf/HTB1CUpQfHsTMeJjy1zcq6xAgXXas/5-m-repose-accessoires-d-coration-de-voiture-POUR-bmw-e46-e39-e36-e90-f30-f10.jpg",
    product:"accessoire",
    price: 2000,
    disc: "",
    quantity: 1,
    totalQty : 100,
  },
   {
     id: 4,
    src: "https://ae01.alicdn.com/kf/HTB1CUpQfHsTMeJjy1zcq6xAgXXas/5-m-repose-accessoires-d-coration-de-voiture-POUR-bmw-e46-e39-e36-e90-f30-f10.jpg",
    product:"accessoire",
    price: 2000,
    disc: "",
    quantity: 1,
    totalQty : 100,
  },
   {
     id: 5,
    src: "https://ae01.alicdn.com/kf/HTB1CUpQfHsTMeJjy1zcq6xAgXXas/5-m-repose-accessoires-d-coration-de-voiture-POUR-bmw-e46-e39-e36-e90-f30-f10.jpg",
    product:"accessoire",
    price: 2000,
    disc: "",
    quantity: 1,
    totalQty : 100,
  },
  {
    id: 6,
    src: "https://ae01.alicdn.com/kf/HTB1CUpQfHsTMeJjy1zcq6xAgXXas/5-m-repose-accessoires-d-coration-de-voiture-POUR-bmw-e46-e39-e36-e90-f30-f10.jpg",
    product:"accessoire",
    price: 2000,
    disc: "",
    quantity: 1,
    totalQty : 100,
  },
 
];
